#!/bin/sh

set -e

echo "Running pre-commit tasks..."

go mod tidy
go generate ./...
go fmt ./...
revive --config revive.toml -formatter friendly ./chainup/...
go test ./...

echo "Pre-commit tasks complete!"
