// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package chainup

import (
	"chainup.dev/chainup/infrastructure"
	"chainup.dev/chainup/provision"
)

// Injectors from inject_memory.go:

func SetupInMemoryApp() *App {
	provider := ProvideFileConfigProvider()
	config := ProvideConfig(provider)
	jobStateMachine := provision.ConfigureJobStateMachine()
	inMemoryJobRepository := provision.NewInMemoryJobRepository()
	provisioner := provision.NewProvisioner(jobStateMachine, inMemoryJobRepository)
	inMemoryServerRepository := infrastructure.NewInMemoryServerRepository()
	app := NewApp(config, provisioner, inMemoryServerRepository)
	return app
}

// Injectors from inject_testing.go:

func SetupTestApp() *App {
	provider := ProvideTestConfigProvider()
	config := ProvideConfig(provider)
	jobStateMachine := provision.ConfigureJobStateMachine()
	inMemoryJobRepository := provision.NewInMemoryJobRepository()
	provisioner := provision.NewProvisioner(jobStateMachine, inMemoryJobRepository)
	inMemoryServerRepository := infrastructure.NewInMemoryServerRepository()
	app := NewApp(config, provisioner, inMemoryServerRepository)
	return app
}
